kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}-{{ template "kube-arangodb-init.name" . }}-clusterroles
subjects:
- kind: ServiceAccount
  name: {{ template "kube-arangodb-init.name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Namespace }}-{{ template "kube-arangodb-init.name" . }}-clusterroles
  apiGroup: rbac.authorization.k8s.io
