{{- if .Values.limits.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu
spec:
  limits:
  - default:
      cpu: {{ .Values.limits.cpuPerContainer.defaultLimit }}
    defaultRequest:
      cpu: {{ .Values.limits.cpuPerContainer.defaultRequest }}
    type: Container

---
apiVersion: v1
kind: LimitRange
metadata:
  name: memory
spec:
  limits:
  - default:
      memory: {{ .Values.limits.memoryPerContainer.defaultLimit }}
    defaultRequest:
      memory: {{ .Values.limits.memoryPerContainer.defaultRequest }}
    type: Container
{{- end }}